/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    media: Media;
    experiences: Experience;
    services: Service;
    testimonials: Testimonial;
    clientLogos: ClientLogo;
    intakeSubmissions: IntakeSubmission;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    experiences: ExperiencesSelect<false> | ExperiencesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    clientLogos: ClientLogosSelect<false> | ClientLogosSelect<true>;
    intakeSubmissions: IntakeSubmissionsSelect<false> | IntakeSubmissionsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    homePage: HomePage;
    aboutPage: AboutPage;
    contactPage: ContactPage;
    portfolioPage: PortfolioPage;
    siteSettings: SiteSetting;
  };
  globalsSelect: {
    homePage: HomePageSelect<false> | HomePageSelect<true>;
    aboutPage: AboutPageSelect<false> | AboutPageSelect<true>;
    contactPage: ContactPageSelect<false> | ContactPageSelect<true>;
    portfolioPage: PortfolioPageSelect<false> | PortfolioPageSelect<true>;
    siteSettings: SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Fotos, logos y videos del sitio. Sube archivos con buena resolución (fotos: mínimo 2000 px de ancho) y sin oscurecer: el sitio aplica sus propios filtros.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe lo que se ve, para personas que usan lector de pantalla y para Google. Ej.: «Equipo pintando un lienzo colectivo en el Taller Florecer».
   */
  alt?: string | null;
  /**
   * Marca esto solo si la imagen es puramente decorativa (texturas, fondos) y no aporta información. Los lectores de pantalla la ignorarán.
   */
  decorativa?: boolean | null;
  /**
   * Fotógrafo o fuente, si aplica. No se muestra en el sitio.
   */
  credito?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Los talleres y experiencias del portafolio. Cada una aparece en /portafolio, en su propia página y en la página de su pilar.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences".
 */
export interface Experience {
  id: number;
  /**
   * Nombre completo. Ej.: «Taller Marca Personal».
   */
  title: string;
  /**
   * Versión breve para tarjetas y etiquetas. Ej.: «Marca Personal».
   */
  tagline: string;
  /**
   * Foto horizontal (16:9) de la experiencia. Aparece en las tarjetas del portafolio y en la página de la experiencia.
   */
  cover: number | Media;
  /**
   * Qué logra esta experiencia, en 1–3 oraciones. Aparece bajo «Objetivo» en la página.
   */
  objetivo: string;
  /**
   * Uno por línea. Aparecen como lista en la página.
   */
  resultados: {
    texto: string;
    id?: string | null;
  }[];
  /**
   * Párrafo que describe la experiencia. Puedes dejarlo vacío si usas solo la lista de temas de abajo.
   */
  contenido?: string | null;
  /**
   * Puntos ordenados del contenido del taller, si aplica.
   */
  contenidoItems?:
    | {
        texto: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Frase que presenta el bloque «Temas a trabajar». Aparece cuando agregas al menos un tema abajo.
   */
  temasIntro?: string | null;
  temas?:
    | {
        texto: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Ej.: «3 horas».
   */
  duracion: string;
  modalidad: string;
  seo?: {
    /**
     * Ideal: hasta 60 caracteres. Google corta los títulos más largos.
     */
    metaTitulo?: string | null;
    /**
     * Resumen de 1–2 oraciones. Ideal: hasta 155 caracteres; Google corta el resto.
     */
    metaDescripcion?: string | null;
    /**
     * Imagen que aparece al compartir el enlace en redes o WhatsApp (horizontal, 1200×630). Opcional: sin ella se usa la imagen general del sitio.
     */
    ogImagen?: (number | null) | Media;
  };
  /**
   * Parte final de la URL (ej. «taller-marca-personal»). Se genera sola desde el título si la dejas vacía. Evita cambiarla después de publicar: los enlaces compartidos dejarían de funcionar.
   */
  slug?: string | null;
  /**
   * A qué pilar pertenece. Define en qué página de servicio aparece.
   */
  pillar: 'desarrollo-profesional' | 'bienestar-corporativo' | 'experiencias-de-integracion';
  /**
   * La experiencia destacada aparece en grande en el inicio. Solo hay una a la vez: al publicar esta como destacada, las demás se desmarcan solas.
   */
  destacada?: boolean | null;
  /**
   * Orden en el portafolio: la más reciente aparece primero.
   */
  fecha?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Los tres pilares de la marca. Cada uno tiene su página en /servicios y su tarjeta en el inicio. Son fijos: se editan, no se agregan ni eliminan.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  /**
   * Tres palabras que abren la página. Ej.: «Crecer. Liderar. Comunicar.»
   */
  tagline: string;
  /**
   * 1–2 oraciones para la tarjeta del pilar en la página de inicio.
   */
  resumen: string;
  /**
   * Párrafo principal de la página del pilar.
   */
  description: string;
  /**
   * A qué equipos o áreas está dirigido este pilar.
   */
  audience: string;
  deliverables: {
    texto: string;
    id?: string | null;
  }[];
  outcomes: {
    texto: string;
    id?: string | null;
  }[];
  /**
   * Foto horizontal (4:3) para la cabecera de la página. Personas en una experiencia real, luz natural, sin oscurecer.
   */
  foto?: (number | null) | Media;
  /**
   * Texto del botón de la cabecera (lleva a Contacto).
   */
  ctaEtiqueta: string;
  /**
   * Sección final que invita a conversar.
   */
  cierre: {
    titulo: string;
    texto: string;
    ctaEtiqueta: string;
  };
  seo?: {
    /**
     * Ideal: hasta 60 caracteres. Google corta los títulos más largos.
     */
    metaTitulo?: string | null;
    /**
     * Resumen de 1–2 oraciones. Ideal: hasta 155 caracteres; Google corta el resto.
     */
    metaDescripcion?: string | null;
    /**
     * Imagen que aparece al compartir el enlace en redes o WhatsApp (horizontal, 1200×630). Opcional: sin ella se usa la imagen general del sitio.
     */
    ogImagen?: (number | null) | Media;
  };
  /**
   * Fija por pilar: el sitio y el formulario de contacto dependen de estas tres direcciones.
   */
  slug: 'desarrollo-profesional' | 'bienestar-corporativo' | 'experiencias-de-integracion';
  /**
   * Icono de la tarjeta en la página de inicio.
   */
  icon: 'graduation-cap' | 'heart' | 'users' | 'sparkles' | 'lightbulb' | 'award';
  /**
   * Posición entre los tres pilares (1, 2, 3).
   */
  orden: number;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Citas de clientes. Los tres marcados como «destacado» aparecen en la página de inicio.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  /**
   * 2–3 oraciones, en palabras del cliente, sobre el impacto en su equipo o cultura. Sin comillas: el sitio las agrega.
   */
  cita: string;
  autor: string;
  /**
   * Ej.: «Dirección de RRHH».
   */
  cargo: string;
  empresa: string;
  /**
   * El inicio muestra exactamente tres testimonios destacados, en el orden indicado abajo.
   */
  destacado?: boolean | null;
  /**
   * Posición entre los destacados (1 = primero).
   */
  orden?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Marcas que aparecen en «Marcas que han confiado en nosotros», en la página de inicio, ordenadas por el campo Orden.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clientLogos".
 */
export interface ClientLogo {
  id: number;
  nombre: string;
  /**
   * PNG con fondo transparente. Se muestra sobre tarjeta blanca, pequeño: usa la versión simple del logo.
   */
  logo: number | Media;
  /**
   * Posición en la cuadrícula (1 = primero).
   */
  orden: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Consultas recibidas desde el formulario de contacto. Si «Correo enviado» está desmarcado, la notificación por correo falló: contacta a ese lead manualmente. Usa «Estado» para llevar el seguimiento.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "intakeSubmissions".
 */
export interface IntakeSubmission {
  id: number;
  companyName: string;
  contactName: string;
  corporateEmail: string;
  phone?: string | null;
  serviceType: 'desarrollo-profesional' | 'bienestar-corporativo' | 'experiencias-de-integracion' | 'no-estoy-seguro';
  participantRange: '1-20' | '20-50' | '50-100' | '100-500' | '500+';
  tentativeDate?: string | null;
  eventFormat: 'presencial' | 'virtual' | 'hibrido';
  eventObjective: string;
  referralSource?: string | null;
  privacyConsent: boolean;
  /**
   * Único campo editable: úsalo para el seguimiento del lead.
   */
  estado: 'nueva' | 'contactada' | 'cerrada';
  /**
   * Lo marca el sistema. Si está desmarcado, el correo de notificación falló y este lead requiere contacto manual.
   */
  correoEnviado?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Personas con acceso a este panel. Los editores gestionan contenido; los administradores además gestionan usuarios y ajustes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Nombre y apellido, como quieres que aparezca en el panel.
   */
  nombre: string;
  /**
   * Editor: crea, edita y publica contenido. Administrador: además gestiona usuarios y configuración.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'experiences';
        value: number | Experience;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'clientLogos';
        value: number | ClientLogo;
      } | null)
    | ({
        relationTo: 'intakeSubmissions';
        value: number | IntakeSubmission;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  decorativa?: T;
  credito?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences_select".
 */
export interface ExperiencesSelect<T extends boolean = true> {
  title?: T;
  tagline?: T;
  cover?: T;
  objetivo?: T;
  resultados?:
    | T
    | {
        texto?: T;
        id?: T;
      };
  contenido?: T;
  contenidoItems?:
    | T
    | {
        texto?: T;
        id?: T;
      };
  temasIntro?: T;
  temas?:
    | T
    | {
        texto?: T;
        id?: T;
      };
  duracion?: T;
  modalidad?: T;
  seo?:
    | T
    | {
        metaTitulo?: T;
        metaDescripcion?: T;
        ogImagen?: T;
      };
  slug?: T;
  pillar?: T;
  destacada?: T;
  fecha?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  tagline?: T;
  resumen?: T;
  description?: T;
  audience?: T;
  deliverables?:
    | T
    | {
        texto?: T;
        id?: T;
      };
  outcomes?:
    | T
    | {
        texto?: T;
        id?: T;
      };
  foto?: T;
  ctaEtiqueta?: T;
  cierre?:
    | T
    | {
        titulo?: T;
        texto?: T;
        ctaEtiqueta?: T;
      };
  seo?:
    | T
    | {
        metaTitulo?: T;
        metaDescripcion?: T;
        ogImagen?: T;
      };
  slug?: T;
  icon?: T;
  orden?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  cita?: T;
  autor?: T;
  cargo?: T;
  empresa?: T;
  destacado?: T;
  orden?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clientLogos_select".
 */
export interface ClientLogosSelect<T extends boolean = true> {
  nombre?: T;
  logo?: T;
  orden?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "intakeSubmissions_select".
 */
export interface IntakeSubmissionsSelect<T extends boolean = true> {
  companyName?: T;
  contactName?: T;
  corporateEmail?: T;
  phone?: T;
  serviceType?: T;
  participantRange?: T;
  tentativeDate?: T;
  eventFormat?: T;
  eventObjective?: T;
  referralSource?: T;
  privacyConsent?: T;
  estado?: T;
  correoEnviado?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  nombre?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Todo el contenido de la página de inicio, sección por sección, en el orden en que aparecen.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homePage".
 */
export interface HomePage {
  id: number;
  hero: {
    /**
     * Línea pequeña sobre el titular. Ej.: «Experiencias corporativas · Desde lo humano».
     */
    eyebrow: string;
    /**
     * Primera parte del titular grande. Ideal: corto; en pantallas pequeñas los titulares largos se parten mal.
     */
    titulo: string;
    /**
     * Cierre del titular, en cursiva y color de marca. Ej.: «las personas crecen.»
     */
    tituloDestacado: string;
    subtitulo: string;
    /**
     * Lleva a Contacto.
     */
    ctaEtiqueta: string;
    /**
     * Video en loop (mp4/webm, máx. 8 MB) o foto horizontal. Mientras esté vacío, el sitio muestra el marcador de posición. No lo oscurezcas: el sitio aplica su propio degradado.
     */
    fondo?: (number | null) | Media;
  };
  /**
   * Franja de logos bajo la portada. Los logos se gestionan en «Logos de clientes».
   */
  marcas: {
    titulo: string;
    texto: string;
  };
  /**
   * Encabezado de la sección. Las tarjetas salen de «Pilares de servicio».
   */
  pilares: {
    tag: string;
    titulo: string;
    descripcion: string;
  };
  sembrando: {
    tag: string;
    titulo: string;
    texto: string;
    /**
     * Dos fotos verticales (3:4) de Proyecto Estrella. Mientras falten, el sitio muestra marcadores de posición.
     */
    fotos?:
      | {
          foto: number | Media;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Sección grande con la experiencia marcada como destacada en «Experiencias».
   */
  destacada: {
    tag: string;
    /**
     * 1–2 oraciones: personas participantes, tipo de experiencia, resultado clave.
     */
    resumen: string;
    /**
     * Ej.: «120+».
     */
    statValor: string;
    /**
     * Ej.: «Personas».
     */
    statEtiqueta: string;
    ctaEtiqueta: string;
  };
  /**
   * Encabezado de la sección. Las citas salen de «Testimonios» (los tres destacados).
   */
  testimonios: {
    tag: string;
    titulo: string;
    descripcion: string;
  };
  seo?: {
    /**
     * Ideal: hasta 60 caracteres. Google corta los títulos más largos.
     */
    metaTitulo?: string | null;
    /**
     * Resumen de 1–2 oraciones. Ideal: hasta 155 caracteres; Google corta el resto.
     */
    metaDescripcion?: string | null;
    /**
     * Imagen que aparece al compartir el enlace en redes o WhatsApp (horizontal, 1200×630). Opcional: sin ella se usa la imagen general del sitio.
     */
    ogImagen?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * La página Nosotros: historia, esencia, valores y arquetipos de la marca (manual Cap. 01–02).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aboutPage".
 */
export interface AboutPage {
  id: number;
  hero: {
    eyebrow: string;
    titulo: string;
    /**
     * Cierre en cursiva. Ej.: «desde las personas.»
     */
    tituloDestacado: string;
    historia: {
      parrafo: string;
      id?: string | null;
    }[];
    /**
     * Foto vertical (3:4): personas conectando en una experiencia real, luz natural. Mientras esté vacía, se muestra el marcador de posición.
     */
    foto?: (number | null) | Media;
  };
  esencia: {
    tag: string;
    /**
     * Ej.: «Transformar».
     */
    titulo: string;
    /**
     * En cursiva. Ej.: «desde lo humano.»
     */
    tituloDestacado: string;
    texto: string;
  };
  valores: {
    tag: string;
    titulo: string;
    /**
     * Los cinco valores del manual de marca (Cap. 02), textuales.
     */
    items: {
      icono: 'graduation-cap' | 'heart' | 'users' | 'sparkles' | 'lightbulb' | 'award';
      titulo: string;
      descripcion: string;
      id?: string | null;
    }[];
  };
  arquetipos: {
    tag: string;
    titulo: string;
    descripcion: string;
    /**
     * Los tres arquetipos del manual de marca (Cap. 02), textuales.
     */
    items: {
      titulo: string;
      descripcion: string;
      id?: string | null;
    }[];
  };
  cierre: {
    titulo: string;
    /**
     * En cursiva.
     */
    tituloDestacado: string;
    ctaEtiqueta: string;
  };
  seo?: {
    /**
     * Ideal: hasta 60 caracteres. Google corta los títulos más largos.
     */
    metaTitulo?: string | null;
    /**
     * Resumen de 1–2 oraciones. Ideal: hasta 155 caracteres; Google corta el resto.
     */
    metaDescripcion?: string | null;
    /**
     * Imagen que aparece al compartir el enlace en redes o WhatsApp (horizontal, 1200×630). Opcional: sin ella se usa la imagen general del sitio.
     */
    ogImagen?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Textos de la página de contacto. Los campos y pasos del formulario son parte del sistema y no se editan aquí; el número de WhatsApp vive en «Ajustes del sitio».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contactPage".
 */
export interface ContactPage {
  id: number;
  header: {
    eyebrow: string;
    titulo: string;
    texto: string;
  };
  /**
   * Línea bajo el formulario que ofrece WhatsApp.
   */
  altContacto: {
    /**
     * Ej.: «¿Prefiere hablar directamente?»
     */
    texto: string;
    /**
     * Ej.: «Escríbanos por WhatsApp».
     */
    etiquetaEnlace: string;
  };
  seo?: {
    /**
     * Ideal: hasta 60 caracteres. Google corta los títulos más largos.
     */
    metaTitulo?: string | null;
    /**
     * Resumen de 1–2 oraciones. Ideal: hasta 155 caracteres; Google corta el resto.
     */
    metaDescripcion?: string | null;
    /**
     * Imagen que aparece al compartir el enlace en redes o WhatsApp (horizontal, 1200×630). Opcional: sin ella se usa la imagen general del sitio.
     */
    ogImagen?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Encabezado de /portafolio. Las tarjetas salen de «Experiencias».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolioPage".
 */
export interface PortfolioPage {
  id: number;
  header: {
    eyebrow: string;
    titulo: string;
    texto: string;
  };
  /**
   * Invitación al final de la página de cada experiencia (compartida por todas).
   */
  cierreExperiencia: {
    titulo: string;
    texto: string;
    ctaEtiqueta: string;
  };
  seo?: {
    /**
     * Ideal: hasta 60 caracteres. Google corta los títulos más largos.
     */
    metaTitulo?: string | null;
    /**
     * Resumen de 1–2 oraciones. Ideal: hasta 155 caracteres; Google corta el resto.
     */
    metaDescripcion?: string | null;
    /**
     * Imagen que aparece al compartir el enlace en redes o WhatsApp (horizontal, 1200×630). Opcional: sin ella se usa la imagen general del sitio.
     */
    ogImagen?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Identidad, contacto, redes, navegación y pie de página — lo que aparece en todas las páginas.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings".
 */
export interface SiteSetting {
  id: number;
  identidad: {
    /**
     * Título por defecto en Google y la pestaña del navegador. Ej.: «ana banana Experiences — Transformar desde lo humano».
     */
    tituloBase: string;
    /**
     * Descripción por defecto para buscadores (ideal: hasta 155 caracteres).
     */
    metaDescripcion: string;
  };
  contacto: {
    email: string;
    /**
     * Solo números, con código de país y sin espacios. Ej.: 50250320841.
     */
    whatsapp: string;
  };
  /**
   * Direcciones completas. Deja vacía una red para ocultarla del pie de página.
   */
  redes?: {
    linkedin?: string | null;
    instagram?: string | null;
    tiktok?: string | null;
  };
  nav: {
    enlaces: {
      etiqueta: string;
      destino:
        | '/contacto'
        | '/portafolio'
        | '/nosotros'
        | '/servicios/desarrollo-profesional'
        | '/servicios/bienestar-corporativo'
        | '/servicios/experiencias-de-integracion'
        | '/';
      id?: string | null;
    }[];
    /**
     * Botón destacado del menú (lleva a Contacto). Ej.: «Conversemos».
     */
    ctaEtiqueta: string;
  };
  footer: {
    /**
     * Ej.: «Transformemos su organización».
     */
    ctaTitulo: string;
    /**
     * En cursiva. Ej.: «desde lo humano.»
     */
    ctaTituloDestacado: string;
    ctaEtiqueta: string;
    /**
     * Párrafo corto junto al logo, en el pie de página.
     */
    blurb: string;
    enlaces: {
      etiqueta: string;
      destino:
        | '/contacto'
        | '/portafolio'
        | '/nosotros'
        | '/servicios/desarrollo-profesional'
        | '/servicios/bienestar-corporativo'
        | '/servicios/experiencias-de-integracion'
        | '/';
      id?: string | null;
    }[];
    /**
     * Aparece en el © del pie. Ej.: «Grupo anabanana, S.A.»
     */
    entidad: string;
    /**
     * Ej.: «Guatemala City, Guatemala».
     */
    ubicacion: string;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homePage_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        titulo?: T;
        tituloDestacado?: T;
        subtitulo?: T;
        ctaEtiqueta?: T;
        fondo?: T;
      };
  marcas?:
    | T
    | {
        titulo?: T;
        texto?: T;
      };
  pilares?:
    | T
    | {
        tag?: T;
        titulo?: T;
        descripcion?: T;
      };
  sembrando?:
    | T
    | {
        tag?: T;
        titulo?: T;
        texto?: T;
        fotos?:
          | T
          | {
              foto?: T;
              id?: T;
            };
      };
  destacada?:
    | T
    | {
        tag?: T;
        resumen?: T;
        statValor?: T;
        statEtiqueta?: T;
        ctaEtiqueta?: T;
      };
  testimonios?:
    | T
    | {
        tag?: T;
        titulo?: T;
        descripcion?: T;
      };
  seo?:
    | T
    | {
        metaTitulo?: T;
        metaDescripcion?: T;
        ogImagen?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aboutPage_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        titulo?: T;
        tituloDestacado?: T;
        historia?:
          | T
          | {
              parrafo?: T;
              id?: T;
            };
        foto?: T;
      };
  esencia?:
    | T
    | {
        tag?: T;
        titulo?: T;
        tituloDestacado?: T;
        texto?: T;
      };
  valores?:
    | T
    | {
        tag?: T;
        titulo?: T;
        items?:
          | T
          | {
              icono?: T;
              titulo?: T;
              descripcion?: T;
              id?: T;
            };
      };
  arquetipos?:
    | T
    | {
        tag?: T;
        titulo?: T;
        descripcion?: T;
        items?:
          | T
          | {
              titulo?: T;
              descripcion?: T;
              id?: T;
            };
      };
  cierre?:
    | T
    | {
        titulo?: T;
        tituloDestacado?: T;
        ctaEtiqueta?: T;
      };
  seo?:
    | T
    | {
        metaTitulo?: T;
        metaDescripcion?: T;
        ogImagen?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contactPage_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  header?:
    | T
    | {
        eyebrow?: T;
        titulo?: T;
        texto?: T;
      };
  altContacto?:
    | T
    | {
        texto?: T;
        etiquetaEnlace?: T;
      };
  seo?:
    | T
    | {
        metaTitulo?: T;
        metaDescripcion?: T;
        ogImagen?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolioPage_select".
 */
export interface PortfolioPageSelect<T extends boolean = true> {
  header?:
    | T
    | {
        eyebrow?: T;
        titulo?: T;
        texto?: T;
      };
  cierreExperiencia?:
    | T
    | {
        titulo?: T;
        texto?: T;
        ctaEtiqueta?: T;
      };
  seo?:
    | T
    | {
        metaTitulo?: T;
        metaDescripcion?: T;
        ogImagen?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  identidad?:
    | T
    | {
        tituloBase?: T;
        metaDescripcion?: T;
      };
  contacto?:
    | T
    | {
        email?: T;
        whatsapp?: T;
      };
  redes?:
    | T
    | {
        linkedin?: T;
        instagram?: T;
        tiktok?: T;
      };
  nav?:
    | T
    | {
        enlaces?:
          | T
          | {
              etiqueta?: T;
              destino?: T;
              id?: T;
            };
        ctaEtiqueta?: T;
      };
  footer?:
    | T
    | {
        ctaTitulo?: T;
        ctaTituloDestacado?: T;
        ctaEtiqueta?: T;
        blurb?: T;
        enlaces?:
          | T
          | {
              etiqueta?: T;
              destino?: T;
              id?: T;
            };
        entidad?: T;
        ubicacion?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}